In [1]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   --- ------------------------------------ 1.6/16.5 MB 8.9 MB/s eta 0:00:02
   ----- ---------------------------------- 2.4/16.5 MB 6.8 MB/s eta 0:00:03
   ------ --------------------------------- 2.9/16.5 MB 5.2 MB/s eta 0:00:03
   -------- ------------------------------- 3.4/16.5 MB 4.5 MB/s eta 0:00:03
   --------- ------------------------------ 3.9/16.5 MB 4.0 MB/s eta 0:00:04
   ---------- ----------------------------- 4.5/16.5 MB 3.7 MB/s eta 0:00:04
   ----------- ---------------------------- 4.7/16.5 MB 3.6 MB/s eta 0:00:04
   ------------ --------------------------- 5.2/16.5 MB 3.1 MB/s eta 0:00:04
   ------------- -------------------------- 5.8/16.5 MB 3.1 MB/s eta 0:00:04
   --------------- ------------------------ 6.3/16.5 MB 3.1 MB/s eta 0:00:04
   ----------------- ---------------------- 7.3/16.5 MB 3.2 MB/s eta 0:00:03
   ------------------- -------------------- 7.9/16.5 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 8.4/16.5 MB 3.1 MB/s eta 0:00:03
   --------------------- ------------------ 8.9/16.5 MB 3.1 MB/s eta 0:00:03
   ----------------------- ---------------- 9.7/16.5 MB 3.0 MB/s eta 0:00:03
   ------------------------ --------------- 10.2/16.5 MB 3.1 MB/s eta 0:00:03
   -------------------------- ------------- 11.0/16.5 MB 3.1 MB/s eta 0:00:02
   ---------------------------- ----------- 11.8/16.5 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 12.3/16.5 MB 3.1 MB/s eta 0:00:02
   ------------------------------- -------- 12.8/16.5 MB 3.0 MB/s eta 0:00:02
   ------------------------------- -------- 13.1/16.5 MB 3.0 MB/s eta 0:00:02
   --------------------------------- ------ 13.6/16.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 14.2/16.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 14.4/16.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 2.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [9]:
import pandas as pd
import mysql.connector
import warnings
warnings.filterwarnings('ignore')

In [10]:
conn = mysql.connector.connect(
    host="18.136.157.135",
    user="dm_team2",
    password="DM!$Team&27@9!20!",
    database="project_sales",
    port=3306
)

In [11]:
query = "SELECT * FROM data"
df = pd.read_sql(query, conn)

df.head()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,,Mode-5,Open
1,14-11-2018 09:22,,Website,XXXXXXX,#VALUE!,Sales-Agent-10,,Mode-5,Open
2,14-11-2018 09:21,,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,,Mode-5,Open
3,14-11-2018 08:46,,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,,Mode-5,Open
4,14-11-2018 07:34,,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,,Mode-5,Open

In [12]:
df.to_csv("sales_dataset.csv", index=False)

In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [14]:
df1 = pd.read_csv(r"C:\Users\Sanjana\Downloads\clint project\sales_dataset.csv")
df1

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,NaN,Mode-5,Open
1,14-11-2018 09:22,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2,14-11-2018 09:21,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
3,14-11-2018 08:46,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
4,14-11-2018 07:34,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
...,...,...,...,...,...,...,...,...,...
7417,28-04-2018 09:45,9.0,Call,NaN,aXXXXXXX@gmail.com,Sales-Agent-6,Mumbai,Mode-4,LOST
7418,28-04-2018 09:43,15.0,Call,NaN,#VALUE!,Sales-Agent-12,Other Locations,Mode-5,LOST
7419,28-04-2018 09:20,5.0,Live Chat-Direct,NaN,sXXXXXXX@gmail.com,Sales-Agent-11,Bangalore,Mode-1,Not Responding
7420,28-04-2018 08:04,21.0,CRM form,NaN,YXXXXXXX@gmail.com,Sales-Agent-4,Other Locations,Mode-1,Just Enquiry
7421,28-04-2018 07:54,25.0,Website,NaN,cXXXXXXX@gmail.com,Sales-Agent-3,Chennai,Mode-1,CONVERTED